version: '3'
services:
  dotnet-app:
    image: abdelkarim793/car:tag
    ports:
      - "1001:80"
    volumes:
      - ./GestionCars.db:/app/GestionCars.db

    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: GestionCars
      MYSQL_USER: root
      MYSQL_PASSWORD:

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GestionCars
      MYSQL_USER: root
      MYSQL_PASSWORD: